/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#e4e2e1',
        surface: '#fcf9f8',
        'on-background': '#1c1b1b',
        'tertiary-fixed': '#e2e2e2',
        'on-error-container': '#93000a',
        primary: '#004ccd',
        'secondary-container': '#e4e2e1',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-secondary-fixed': '#1b1c1c',
        'outline-variant': '#c3c6d8',
        'primary-container': '#0f62fe',
        'surface-tint': '#0052dd',
        'inverse-primary': '#b4c5ff',
        'surface-container': '#f0edec',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#b4c5ff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        outline: '#737687',
        background: '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1c1b1b',
        'error-container': '#ffdad6',
        'on-surface-variant': '#424656',
        secondary: '#5f5e5e',
        'on-secondary-container': '#656464',
        'surface-container-low': '#f6f3f2',
        'on-tertiary-container': '#f5f4f4',
        'inverse-on-surface': '#f3f0ef',
        'on-tertiary-fixed-variant': '#454747',
        'surface-variant': '#e5e2e1',
        'on-tertiary-fixed': '#1a1c1c',
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#c8c6c6',
        'on-primary-fixed-variant': '#003da9',
        'on-primary-container': '#f3f3ff',
        'surface-bright': '#fcf9f8',
        'primary-fixed': '#dbe1ff',
        'on-secondary-fixed-variant': '#474747',
        'surface-dim': '#dcd9d9',
        'inverse-surface': '#313030',
        'surface-container-high': '#eae7e7',
        'on-primary-fixed': '#00174c',
        tertiary: '#565758',
        'tertiary-container': '#6f7070',
        'surface-container-highest': '#e5e2e1',
        remove: '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        xl: '32px',
        base: '16px',
        'margin-desktop': '32px',
        gutter: '16px',
        md: '16px',
        lg: '24px',
        'margin-mobile': '16px',
        sm: '8px',
      },
      fontFamily: {
        sans: ['IBM Plex Sans', 'sans-serif'],
        code: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.32px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0px', fontWeight: '400' }],
        'display-01': ['42px', { lineHeight: '50px', letterSpacing: '0px', fontWeight: '300' }],
        'label-bold': ['12px', { lineHeight: '16px', letterSpacing: '0.32px', fontWeight: '600' }],
        code: ['12px', { lineHeight: '16px', letterSpacing: '0px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.16px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '26px', letterSpacing: '0px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
